### ISSUE TITLE
UnicodeDecodeError - Error 500

### ISSUE THREAD

**Issue by Percent01** [koniu/recoll-webui#32]
Hi,

I get his error message, when I would like to search something in specific directory. (the directory include special eastern europe character)

Error 500: Internal Server Error
Sorry, the requested URL 'http://xxxxxx.com/results?query=&dir=search_directory%2FPodiv%C3%ADnsk&after=&before=&sort=relevancyrating&ascending=0&page=1' caused an error:

Internal Server Error
Exception:

UnicodeDecodeError('ascii', ' dir:"output/Podiv\xc3\xadnsk" ', 45, 46, 'ordinal not in range(128)')
Traceback:

Traceback (most recent call last):
  File "/Desktop/recoll/recoll-webui/bottle.py", line 744, in _handle
    return route.call(**args)
  File "/Desktop/recoll/recoll-webui/bottle.py", line 1479, in wrapper
    rv = callback(*a, **ka)
  File "/Desktop/recoll/recoll-webui/bottle.py", line 2850, in wrapper
    result = func(*args, **kwargs)
  File "/Desktop/recoll/recoll-webui/webui.py", line 240, in results
    qs = query_to_recoll_string(query)
  File "/Desktop/recoll/recoll-webui/webui.py", line 151, in query_to_recoll_string
    qs += " dir:\"%s\" " % q['dir']
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 45: ordinal not in range(128)

---
I modified the pasted URL.

**Comment by koniu** [comment]
no reply
