### ISSUE TITLE
Problem with running webui-standalone.py

### ISSUE THREAD

**Issue by MartinEichner** [koniu/recoll-webui#60]
I have downloaded and unpacked "recoll-webui-master.zip" and I try to start the standalone version by running the command ./webui-standalone.py on a bash command line, but I receive the following output:
Traceback (most recent call last):
  File "./webui-standalone.py", line 4, in <module>
    import webui
  File "/home/eichner/Desktop/recoll-webui-master/webui.py", line 23, in <module>
    import recoll
ImportError: No module named recoll
I have also tried adding the command line arguments "-a" and "-p", but that does not resolve the issue. What do I do wrong? System information: recoll 1.13.7 + Xapian 1.2.22 are running successfully on a machine with Linux Mint 18.3 (64bit) and Mate 1.18.0 (Linux Kernel 4.10.0-38-generic x86_64).

**Comment by kero99** [comment]
sudo apt-get install python-recoll

Done ;)

**Comment by MartinEichner** [comment]
Thank you. This solved my problem. 
At least, I no longer receive this error message. After sending the command, I get

:3:common/rclinit.cpp:308::Configuration directory: /home/eichner/.recoll
Bottle server starting up (using WSGIRefServer())...
Listening on http://localhost:8080/
Hit Ctrl-C to quit.

I expected that a user-interface would open next, but nothing happened for quite a long time. Do I need to channel the output into firefox somehow although this is the standalone version? Or is this a problem caused by a firewall?

**Comment by koniu** [comment]
This is a web-based user interface so you need to open it in a browser (the
name "standalone" refers to using a built-in http server rather than nginx
or apache).

Go to http://localhost:8080 in your web browser.

Also, Recoll itself needs to be configured before you can use the webui.

**Comment by MartinEichner** [comment]
Thank you. This worked.
