### ISSUE TITLE
Problem with running webui-standalone.py in windows

### ISSUE THREAD

**Issue by Sathishkrishn** [koniu/recoll-webui#62]
I got recoll-webui and ran webui-standalon.py on cmd, but I get this error. Traceback (most recent call last):
File "./webui-standalone.py", line 3, in
import webui
File "/media/daten/download/recoll-webui/webui.py", line 6, in
import recoll
ImportError: No module named recoll
Does this work on Windows? I'm not sure about this. Clarify

**Comment by gekke158** [comment]
Hi @medoc92 : Do you see any way of getting the WebUI to run on a Windows Server? Thanks

**Comment by medoc92** [comment]
As mentionned above, the Recoll Python module was not ported to Windows. It's probably feasible, but quite a bit of work. I have no motivation to do it except maybe if someone pays for it (I'd have to take a closer look first).

I think that the easiest approach for doing this actually would be to run recoll and the webui in a Linux VM on the Windows server.

**Comment by medoc92** [comment]
I had a quick look and building/using the extension under Windows is probably not going to be a piece of cake. For example: the standard Python is built with the Microsoft compiler but Recoll currently uses mingw, so we'd need to either build Recoll with MSVC, which I had initially tried for the port, with no success, or use a MinGW build of Python. So let me know how it goes with the VM approach. Don't hesitate to reach me at jf@recoll.org if you have issues.
