### ISSUE TITLE
Recoll Web UI Error 500 (WSGI)

### ISSUE THREAD

**Issue by KlausItem** [koniu/recoll-webui#73]
Hello,

all of a sudden I got ERROR 500 sometimes if i search with the WEB UI.
most of the times when the string is long or has text and numbers. Short words always works.
On the Desktop App everything is good.

Error like This:
Sorry, the requested URL 'http://xxx.xxx.xxx.xxx/recoll/results?query=welivesecurity&dir=%3Call%3E&after=&before=&sort=relevancyrating&ascending=0&page=1' caused an error:

on the apache2 errorlog it says:

[Wed Mar 13 08:22:45.944614 2019] [wsgi:error] [pid 29405:tid 140175114483456] [remote xxx.xxx.xxx.xxx:0] Traceback (most recent call last):
[Wed Mar 13 08:22:45.944736 2019] [wsgi:error] [pid 29405:tid 140175114483456] [remote xxx.xxx.xxx.xxx:0]   File "/var/www/recoll-webui-master/bottle.py", line 744, in _handle
[Wed Mar 13 08:22:45.944744 2019] [wsgi:error] [pid 29405:tid 140175114483456] [remote xxx.xxx.xxx.xxx:0]     return route.call(**args)
[Wed Mar 13 08:22:45.944750 2019] [wsgi:error] [pid 29405:tid 140175114483456] [remote xxx.xxx.xxx.xxx:0]   File "/var/www/recoll-webui-master/bottle.py", line 1479, in wrapper
[Wed Mar 13 08:22:45.944756 2019] [wsgi:error] [pid 29405:tid 140175114483456] [remote xxx.xxx.xxx.xxx:0]     rv = callback(*a, **ka)
[Wed Mar 13 08:22:45.944761 2019] [wsgi:error] [pid 29405:tid 140175114483456] [remote xxx.xxx.xxx.xxx:0]   File "/var/www/recoll-webui-master/bottle.py", line 2850, in wrapper
[Wed Mar 13 08:22:45.944767 2019] [wsgi:error] [pid 29405:tid 140175114483456] [remote xxx.xxx.xxx.xxx:0]     result = func(*args, **kwargs)
[Wed Mar 13 08:22:45.944773 2019] [wsgi:error] [pid 29405:tid 140175114483456] [remote xxx.xxx.xxx.xxx:0]   File "/var/www/recoll-webui-master/webui.py", line 252, in results
[Wed Mar 13 08:22:45.944779 2019] [wsgi:error] [pid 29405:tid 140175114483456] [remote xxx.xxx.xxx.xxx:0]     res, nres, timer = recoll_search(query)
[Wed Mar 13 08:22:45.944785 2019] [wsgi:error] [pid 29405:tid 140175114483456] [remote xxx.xxx.xxx.xxx:0]   File "/var/www/recoll-webui-master/webui.py", line 216, in recoll_search
[Wed Mar 13 08:22:45.944791 2019] [wsgi:error] [pid 29405:tid 140175114483456] [remote xxx.xxx.xxx.xxx:0]     v = getattr(doc, f)
[Wed Mar 13 08:22:45.944796 2019] [wsgi:error] [pid 29405:tid 140175114483456] [remote xxx.xxx.xxx.xxx:0] AttributeError: 'NoneType' object has no attribute 'ipath'

Has annyone an Idea ???

**Comment by medoc92** [comment]
think that this is fixed in:
https://opensourceprojects.eu/p/recollwebui/code/
which is where I (recoll dev) maintain the webui until koniu reappears.

**Comment by bheorcnh** [comment]
This issue is a duplicate of https://github.com/koniu/recoll-webui/issues/75

**Comment by 0000vt** [comment]
> think that this is fixed in:
> https://opensourceprojects.eu/p/recollwebui/code/
> which is where I (recoll dev) maintain the webui until koniu reappears.

Looks like opensourceprojects.eu is down with a 502 error. Is there another way to retrieve the fixed code?
