### ISSUE TITLE
AttributeError("'NoneType' object has no attribute 'ipath'",)

### ISSUE THREAD

**Issue by bubblefish432** [koniu/recoll-webui#75]
Hallo,

Yesterday i become the error:

```
Sorry, the requested URL 'http://omv2:8088/results?query=trapez&dir=%3Call%3E&after=&before=&sort=relevancyrating&ascending=0&page=1' caused an error:

Internal Server Error

Exception:

AttributeError("'NoneType' object has no attribute 'ipath'",)

Traceback:

Traceback (most recent call last):
  File "/media/53db9167-314a-44c9-ba9a-d29ea28404f6/www/recoll-webui/bottle.py", line 744, in _handle
    return route.call(**args)
  File "/media/53db9167-314a-44c9-ba9a-d29ea28404f6/www/recoll-webui/bottle.py", line 1479, in wrapper
    rv = callback(*a, **ka)
  File "/media/53db9167-314a-44c9-ba9a-d29ea28404f6/www/recoll-webui/bottle.py", line 2850, in wrapper
    result = func(*args, **kwargs)
  File "/media/53db9167-314a-44c9-ba9a-d29ea28404f6/www/recoll-webui/webui.py", line 252, in results
    res, nres, timer = recoll_search(query)
  File "/media/53db9167-314a-44c9-ba9a-d29ea28404f6/www/recoll-webui/webui.py", line 216, in recoll_search
    v = getattr(doc, f)
AttributeError: 'NoneType' object has no attribute 'ipath'

```

Can everyone help me ?

**Comment by medoc92** [comment]
I think that this is fixed in:
https://opensourceprojects.eu/p/recollwebui/code/
which is where I (recoll dev) maintain the webui until koniu reappears.

**Comment by bheorcnh** [comment]
I confirm that the fix in the mentioned source location above works for me (I am not the author of this bug).
