### ISSUE TITLE
linux error trying to run webui

### ISSUE THREAD

**Issue by jimrome** [koniu/recoll-webui#83]
On OpenSUSE, I try to run webui-standalone.py, and get"
`/var/recoll-webui-master> ./webui-standalone.py &
[2] 8725
jar@jarfx:/var/recoll-webui-master> Traceback (most recent call last):
  File "./webui-standalone.py", line 5, in <module>
    import webui
  File "/var/recoll-webui-master/webui.py", line 25, in <module>
    from recoll import recoll,rclextract
ImportError: No module named recoll
`
How do I fix this? recoll is in /usr/bin

**Comment by koniu** [comment]
Looks like you're either missing the recoll python bindings or the environment you're running recoll-webui from can't find it. Dont know much about opensuse but seems their recoll package should include the python bindings. Did you install recoll from a package? Could it be that recoll-webui is running with python2 and the recoll python bindings are installed for python3?  TYou might want to try https://framagit.org/medoc92/recollwebui/ - medoc92 (main recoll developer) has been maintaing a fork to keep up with developments.
