### ISSUE TITLE
After indexing the first file, webui no longer works

### ISSUE THREAD

**Issue by tweak19** [koniu/recoll-webui#84]
Hello everybody,
I'm not sure if development is still in progress for this project, but I'll try to add my problem anyway.

So, i added one file to the index of recoll and it stops working. I was able to search with the webui, now i get the following error:

```
Traceback (most recent call last):
  File "/home/pi/document-vault/recoll-webui/bottle.py", line 744, in _handle
    return route.call(**args)
  File "/home/pi/document-vault/recoll-webui/bottle.py", line 1479, in wrapper
    rv = callback(*a, **ka)
  File "/home/pi/document-vault/recoll-webui/bottle.py", line 2850, in wrapper
    result = func(*args, **kwargs)
  File "/home/pi/document-vault/recoll-webui/webui.py", line 250, in main
    config = get_config()
  File "/home/pi/document-vault/recoll-webui/webui.py", line 125, in get_config
    config[k] = type(v)(value)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

System is:
```
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

Recoll Version: 1.24.3 + Xapian 1.4.11
Recoll-webui = git from master

Thanks for your help!

**Comment by sokoow** [comment]
+1 here

**Comment by erkswede** [comment]
+1 Same for me

**Comment by tweak19** [comment]
Sorry for my late replay, but i could fixe this issue by using an fork from this project which look like to be in development state
https://framagit.org/medoc92/recollwebui/
