### ISSUE TITLE
except re.error, e:

### ISSUE THREAD

**Issue by AtomicNess123** [koniu/recoll-webui#88]
I get this error. What am I missing? Thanks!

```shell
Traceback (most recent call last):
  File "webui-standalone.py", line 4, in <module>
    import webui
  File "/Users/user/Downloads/recoll-webui/webui.py", line 4, in <module>
    import bottle
  File "/Users/user/Downloads/recoll-webui/bottle.py", line 380
    except re.error, e:
                   ^
SyntaxError: invalid syntax

```

**Comment by mikec85** [comment]
getting the same error,  did you find a solution?

**Comment by AtomicNess123** [comment]
Unfortunately no. I believe this project is dead.

**Comment by medoc92** [comment]
You're trying to run python2 code with python3.

The WebUI is still maintained with recoll on its repo web site (framagit): https://framagit.org/medoc92/recollwebui

The version there has been updated for python3 (quite some time ago...)
Also see this comment from koniu for confirmation: https://github.com/koniu/recoll-webui/issues/83#issuecomment-723658259
